### ISSUE TITLE
Broken link to branch-a in README.md

### ISSUE THREAD

**Issue by dineshpinto** [alan-turing-institute/CompEnv-Ex3#5]
The link to branch-a is broken in Exercise 3.

BROKEN LINK:
https://github.com/alan-turing-institute/CompEnv-Ex3/tree/branch-1

FIXED LINK:
https://github.com/alan-turing-institute/CompEnv-Ex3/tree/branch-a

**Comment by sgibson91** [comment]
fixed by #6
